### ISSUE TITLE
workplan

### ISSUE THREAD

**Issue by yaronvel** [nivertech/ethersecret#1]
ZVI

- [ ] setup private ethereum blockchain
- [ ] network id 347965709
- [ ] premine to 0x6d87462cB31C1217cf1eD61B4FCC37F823c61624
- [ ] geth with json rpc 
- [ ] server

YARON + EREZ
- [ ] python for encryption, decryption and talking with geth.
